var requirejs,require,define;
(function(c){function e(a,d){var b,f,g,c,e,h,p,k,m,l=d&&d.split("/"),t=q.map,n=t&&t["*"]||{};if(a&&"."===a.charAt(0))if(d){l=l.slice(0,l.length-1);a=l.concat(a.split("/"));for(k=0;k<a.length;k+=1)if(b=a[k],"."===b)a.splice(k,1),k-=1;else if(".."===b)if(1===k&&(".."===a[2]||".."===a[0]))break;else 0<k&&(a.splice(k-1,2),k-=2);a=a.join("/")}else 0===a.indexOf("./")&&(a=a.substring(2));if((l||n)&&t){b=a.split("/");for(k=b.length;0<k;k-=1){f=b.slice(0,k).join("/");if(l)for(m=l.length;0<m;m-=1)if(g=t[l.slice(0,
m).join("/")])if(g=g[f]){c=g;e=k;break}if(c)break;!h&&(n&&n[f])&&(h=n[f],p=k)}!c&&h&&(c=h,e=p);c&&(b.splice(0,e,c),a=b.join("/"))}return a}function b(a,d){return function(){return p.apply(c,w.call(arguments,0).concat([a,d]))}}function a(a){return function(d){return e(d,a)}}function g(a){return function(d){k[a]=d}}function f(a){if(r.call(t,a)){var d=t[a];delete t[a];s[a]=!0;l.apply(c,d)}if(!r.call(k,a)&&!r.call(s,a))throw Error("No "+a);return k[a]}function d(a){var d,b=a?a.indexOf("!"):-1;-1<b&&(d=
a.substring(0,b),a=a.substring(b+1,a.length));return[d,a]}function m(a){return function(){return q&&q.config&&q.config[a]||{}}}var l,p,h,n,k={},t={},q={},s={},r=Object.prototype.hasOwnProperty,w=[].slice;h=function(b,g){var c,k=d(b),h=k[0];b=k[1];h&&(h=e(h,g),c=f(h),b||(b=g));h?b=c&&c.normalize?c.normalize(b,a(g)):e(b,g):(b=e(b,g),k=d(b),h=k[0],b=k[1],h&&(c=f(h)));return{f:h?h+"!"+b:b,n:b,pr:h,p:c}};n={require:function(a){return b(a)},exports:function(a){var b=k[a];return"undefined"!==typeof b?b:
k[a]={}},module:function(a){return{id:a,uri:"",exports:k[a],config:m(a)}}};l=function(a,d,e,p){var l,m,q,u,v=[],A;p=p||a;if("function"===typeof e){d=!d.length&&e.length?["require","exports","module"]:d;for(u=0;u<d.length;u+=1)if(q=h(d[u],p),m=q.f,"require"===m)v[u]=n.require(a);else if("exports"===m)v[u]=n.exports(a),A=!0;else if("module"===m)l=v[u]=n.module(a);else if(r.call(k,m)||r.call(t,m)||r.call(s,m))v[u]=f(m);else if(q.p)q.p.load(q.n,b(p,!0),g(m),{}),v[u]=k[m];else throw Error(a+" missing "+
m);d=e.apply(k[a],v);if(a)if(l&&l.exports!==c&&l.exports!==k[a])k[a]=l.exports;else if(d!==c||!A)k[a]=d}else a&&(k[a]=e)};requirejs=require=p=function(a,d,b,g,e){if("string"===typeof a)return n[a]?n[a](d):f(h(a,d).f);a.splice||(q=a,d.splice?(a=d,d=b,b=null):a=c);d=d||function(){};"function"===typeof b&&(b=g,g=e);g?l(c,a,d,b):setTimeout(function(){l(c,a,d,b)},4);return p};p.config=function(a){q=a;return p};define=function(a,d,b){d.splice||(b=d,d=[]);!r.call(k,a)&&!r.call(t,a)&&(t[a]=[a,d,b])};define.amd=
{jQuery:!0}})();define("../vendor/cell/almond",function(){});define("cell/util/hash",[],function(){var c;c=0;return function(e){var b;return"object"===(b=typeof e)&&null!==e?e.$$hashkey||(e.$$hashkey=""+ ++c):b+":"+e}});define("cell/util/type",{isA:Array.isArray||function(c){return c instanceof Array},isS:function(c){return"string"===typeof c},isF:function(c){return"function"===typeof c}});
define("cell/util/extend",[],function(){return function(c){var e,b,a,g,f,d;a=this;e=function(){if(!(this instanceof e))return e.apply(new b,arguments);(f||a).apply(this,arguments);return this};e.extend=a.extend;g=function(){};g.prototype=a.prototype;b=function(){};g=b.prototype=e.prototype=new g;if(c){c.hasOwnProperty("constructor")&&(f=c.constructor);for(d in c)g[d]=c[d];f&&(g.constructor=f)}return e}});
define("cell/util/ev",{rm:function(c,e,b){var a,g,f;g=-1;for(f="number"===typeof b;a=c[++g];)(f?a[b]===e:a[0]===e&&a[1]===b)&&c.splice(g--,1)}});var __slice=[].slice;
define("cell/Events",["cell/util/hash","cell/util/type","cell/util/extend","cell/util/ev"],function(c,e,b,a){var g,f;f=function(a,b,g){for(var c;c=a.pop();)c[0].apply(c[1],[b].concat(g))};g=function(){c(this);this._e={all:[]}};g.extend=b;g.prototype={constructor:g,on:function(a,b,g){var c;if(this._e&&e.isS(a)&&e.isF(b))return((c=this._e)[a]||(c[a]=[])).push([b,g]),!0},off:function(b,g,c){var f,e;if(this._e){e=null!=b?{type:this._e[b]}:this._e;if(null!=g)null==c&&(c=0);else if(null!=c)g=c,c=1;else return;
for(b in e)(f=e[b])&&a.rm(f,g,c)}},trigger:function(){var a,b,c;b=arguments[0];a=2<=arguments.length?__slice.call(arguments,1):[];this._e&&(f(this._e.all.concat(this._e[b]||[]),b,a),(c=this.parent)&&c.trigger.apply(c,[b].concat(a)))},destroy:function(){var a;if(a=this._e)delete this._e,f(a.all.concat(a.destroy||[]),"destroy",this)}};return g});
define("cell/util/fn",{b:function(c,e){return function(){return c.apply(e,arguments)}},b0:function(c,e){return function(){return c.call(e)}},b1:function(c,e){return function(b){return c.call(e,b)}},b2:function(c,e){return function(b,a){return c.call(e,b,a)}}});define("cell/dom/browser",{msie:+(/msie (\d+)/.exec(navigator.userAgent.toLowerCase())||[])[1]});
define("cell/util/defer",["cell/dom/browser"],function(c){var e,b;if(window.setImmediate)return setImmediate;if(9>c.msie)return setTimeout;e=0;b={};c=function(a){if(b[a=a.data])b[a](),delete b[a]};window.attachEvent?attachEvent("onmessage",c):window.addEventListener("message",c);return function(a){var c;b[c=e++]=a;postMessage(c,"*")}});
define("cell/util/spy",["cell/util/hash","cell/util/fn","cell/util/type","cell/util/defer"],function(c,e,b,a){var g,f,d,m,l,p,h,n,k;l=!1;p=h=void 0;f={};n={};k=function(){var a,b;l=!1;a=f;f={};for(b in a)d(a[b])};m=function(){f[this.$$hashkey||c(this)]=this;l||(l=!0,a(k))};g=function(){this.sig="";this.log={};this.col={}};return{_eam:d=function(a){var b,d,c,f,e;f=h;p=a.scope;h=new g;e=a.e();if(h.sig!==p.sig){c=p.log;d=h.log;for(b in h.col)d["add"+b]={o:h.col[b],e:"add"},d["remove"+b]={o:h.col[b],
e:"remove"};for(b in d)if(c[b])delete c[b];else d[b].o.on(d[b].e,m,a);for(b in c)c[b].o.off(c[b].e,void 0,a);a.scope=h}h=f;a.f(e)},addCol:function(){var a;if(h&&!h.col[a=this.$$hashkey])h.sig+=a,h.col[a]=this},addModel:function(a){var b,d,c;h&&(b=a+((c=this.parent)&&h.col[d=c.$$hashkey]?d:(c=this).$$hashkey),h.log[b]||(h.sig+=b,h.log[b]={o:c,e:a}))},suspendWatch:function(a){var b;b=h;h=void 0;try{a()}catch(d){}h=b},unwatch:function(a){var b,d,g;if(g=n[a=c(a)]){delete n[a];for(d=0;b=g[d++];)for(a in b.scope.log)b.scope.log[a].o.off(void 0,
void 0,b)}},watch:function(a,f,k,h){var p;h||(h=a);if(b.isF(f))return(n[p=c(a)]||(n[p]=[])).push(a={e:e.b0(f,a),f:e.b1(k,h),scope:new g}),d(a),a;k.call(h,f)}}});
define("cell/Model",["cell/util/type","cell/Events","cell/util/spy"],function(c,e,b){return e.extend({constructor:function(a){var b,c;this._a=null!=a?a:{};e.call(this);this.parent=void 0;c=this._a;for(b in c)a=c[b],a instanceof e&&(a.parent=this)},attributes:function(){var a,b;this._s("all");b={};for(a in this._a)b[a]=this._a[a];return b},get:function(a){this._s("change:"+a);return this._a[a]},set:function(a,b){var f;f=this._a[a];if(c.isS(a)&&f!==b)return f instanceof e&&delete f.parent,b instanceof
e&&(b.parent=this),this.trigger("change:"+a,this,this._a[a]=b,f),!0},destroy:function(){var a;e.prototype.destroy.call(this);this.parent&&null!=(a=this.parent)&&a.remove([this]);delete this._a;this.destroy=this.attributes=this.get=this.set=function(){}},_s:b.addModel})});
define("cell/Collection",["cell/Events","cell/util/type","cell/Model","cell/util/spy"],function(c,e,b,a){var g,f;f=function(a,b,c){return Function.call(void 0,"f","c","d","if(this._i){this._s();if(f==null)return;"+("var i=-1,t=this,l=t.length(),e"+(b||"")+";")+"while(++i<l){e=t._i[i];"+a+("}"+(c||"")+"}"))};return g=c.extend({constructor:function(a){c.call(this);this._i=[];this.add(a)},model:b,at:function(a){if(this._i)return this._s(),this._i[a]},length:function(){if(this._i)return this._s(),this._i.length},
indexOf:Array.prototype.indexOf?function(a){if(this._i)return this._s(),this._i.indexOf(a)}:f("if(e===f){return i}","","return -1"),toArray:function(){if(this._i)return this._s(),this._i.slice()},each:f("if(f.call(c,e,i,t)===!1)i=l"),map:f("r.push(f.call(c,e,i,t))",",r=[]","return r"),reduce:f("f=c.call(d,f,e,i,t)","","return f"),filterBy:f('for(k in f)if((v=f[k])==null||v===(x=e.get(k))||(typeof v=="function"&&v(x)))r.push(e)',",k,v,x,r=[]","return r"),pipe:function(a){var b,c,f,h;if(this._i){b=
this;f=0;for(h=a.length;f<h;f++)if(c=a[f],e.isA(b=c.run(b)))b=new g(b);return b}},add:function(a,b){var c,f;if(this._i&&a){a=e.isA(a)?a.slice():[a];c=-1;f=a.length;for(null==b&&(b=this.length());++c<f;)this._i.splice(b++,0,a[c]=this._toM(a[c]));this.trigger("add",a,this,b-f)}},remove:function(a){var b,c,f,g,n,k;if(this._i&&a){e.isA(a)||(a=[a]);b=-1;g=a.length;k=[];for(f=[];++b<g;)if(n=a[b],-1<(c=this.indexOf(n)))delete n.parent,k.push(n),f.push(c),this._i.splice(c,1);f.length&&this.trigger("remove",
k,this,f)}},destroy:function(){this._i&&(c.prototype.destroy.call(this),delete this._i)},_toM:function(a){a=a instanceof this.model?a:new b(a);a.parent=this;return a},_s:a.addCol})});define("models/Todos",["cell/Collection"],function(c){var e,b,a;a=[];for(e=b=1;10>=b;e=++b)a.push({text:""+e,done:!1});return new c(a)});
define("cell/dom/data",[],function(){var c,e,b;b=1;c={};e="dom-"+(new Date).getTime();return{get:function(a,g){var f,d,m;m=null==g;(f=a[e])?d=c[f]:m&&(c[a[e]=b++]=d={});if(d)return m?d:d[g]},set:function(a,g,f){var d;(d=a[e])?c[d][g]=f:(c[a[e]=b++]=a={},a[g]=f)},remove:function(a,b){var f,d;if((f=a[e])&&(d=c[f]))null!=b?delete d[b]:(d.handle&&d.handle.destroy&&d.handle.destroy(),delete c[f],a[e]=void 0)}}});
define("cell/dom/events",["cell/util/ev","cell/dom/browser","cell/dom/data"],function(c,e,b){var a,g,f,d,m,l;g=window.document.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:function(a,b,c){a.attachEvent("on"+b,c)};l=window.document.removeEventListener?function(a,b,c){a.removeEventListener(b,c,!1)}:function(a,b,c){a.detachEvent("on"+b,c)};d=function(){a(this.elem,this.events)};f=function(a,b){var c;c=function(c,f){var d,g,m,l,n;c.preventDefault||(c.preventDefault=function(){c.returnValue=
!1});c.stopPropagation||(c.stopPropagation=function(){c.cancelBubble=!0});c.target||(c.target=c.srcElement||document);null==c.defaultPrevented&&(m=c.preventDefault,c.preventDefault=function(){c.defaultPrevented=!0;m.call(c)},c.defaultPrevented=!1);c.isDefaultPrevented=function(){return c.defaultPrevented};if(d=b[f||c.type]){l=0;for(n=d.length;l<n;l++)g=d[l],g[0].call(g[1]||a,c)}8>=e.msie?(c.preventDefault=null,c.stopPropagation=null,c.isDefaultPrevented=null):(delete c.preventDefault,delete c.stopPropagation,
delete c.isDefaultPrevented)};c.elem=a;c.events=b;c.destroy=d;return c};a=function(a,b){for(var c in b)l(a,c,b[c]),delete b[c]};return{on:m=function(a,c,d,e){var l,q,s,r;if(!(s=b.get(a,"events")))b.set(a,"events",s={});if(!(r=b.get(a,"handle")))b.set(a,"handle",r=f(a,s));if(!(q=s[c]))"mouseenter"===c||"mouseleave"===c?(l=0,s.mouseenter=[],s.mouseleave=[],m(a,"mouseover",function(a){l++;if(1===l)return r(a,"mouseenter")}),m(a,"mouseout",function(a){l--;if(0===l)return r(a,"mouseleave")})):(g(a,c,r),
s[c]=[]),q=s[c];q.push([d,e])},off:function(f,d,e){var g;if(g=b.get(f,"events"))null!=d?null!=e?c.rm(g[d],e,0):(l(f,d,g[d]),delete g[d]):a(f,g)}}});define("cell/Ext",["cell/util/extend","cell/util/spy"],function(c,e){var b;b=function(a){this.options=null!=a?a:{}};b.prototype.watch=function(a,b){e.watch(this.view,a,b,this)};b.prototype.run=function(a,b){this.el=a;this.view=b;this.render()};b.extend=c;return b});
define("cell/exts/x_model",["cell/dom/events","cell/Ext"],function(c,e){var b,a;b={input:{text:a={e:"keyup",g:"value",s:function(a){null!=a&&(this.el[this.a]=a)}},checkbox:{e:"change",g:"checked",s:function(a){this.el[this.a]=!!a}}},select:{e:"change",g:a.g,s:a.s},textarea:a};return e.extend({constructor:function(a,b){this.prop=a;this.model=b;e.call(this)},render:function(){var a,f,d,e,l;a=this.el;f=this.model||this.view.model;e=this.prop;if(d=b[l=a.tagName.toLowerCase()])"input"===l&&(d=d[a.type]);
d&&(this.a=d.g,c.on(a,d.e,function(){f.set(e,a[d.g])}),this.watch(function(){return f.get(e)},d.s))}})});
define("cell/dom/class",[],function(){var c,e;c=/[\t\r\n]/g;e=function(b){return b&&b.replace(/^\s+|\s+$/g,"")};return{add:function(b,a){var g;a&&(b.className=b.className?(g=(" "+b.className+" ").replace(c," "),g.indexOf(0>" "+a+" ")?e(g+a):b.className):a)},remove:function(b,a){var c;a&&b.className&&(c=RegExp(" "+a,"g"),b.className=e((" "+b.className+" ").replace(c,"")))},has:function(b,a){return-1<(" "+b.className+" ").replace(c," ").indexOf(" "+a+" ")}}});
define("cell/exts/x_class",["cell/Ext","cell/util/fn","cell/util/type","cell/dom/class"],function(c,e,b,a){return c.extend({render:function(){var b,c,d,e,l=this;if((c=this.options)&&c.constructor===Object)for(b in e=function(b){l.watch(d,function(c){(c?a.add:a.remove)(this.el,b)})},c)d=c[b],e(b)}})});
define("cell/defineView",["cell/View"],function(c){var e;e=window.__installedViews||{};return{pluginBuilder:"cell/defineView-builder-plugin",load:function(b,a,g,f){e[b]||(e[b]=!0,f=document.createElement("link"),f.href=a.toUrl(b+".css"),f.rel="stylesheet",f.type="text/css",(document.head||document.getElementsByTagName("head")[0]).appendChild(f));g(function(a){a||(a={});a.className=a._cellName=/(.*\/)?(.*)$/.exec(b)[2];return c.extend(a)})}}});
define("cell/dom/mutate",["cell/dom/data"],function(c){var e;e=function(b){var a,g;if(3!==b.nodeType){c.remove(b);b=b.children;g=b.length;for(a=-1;++a<g;)e(b[a])}};return{remove:function(b){var a;e(b);(a=b.parentNode)&&a.removeChild(b)}}});
define("cell/View","cell/Collection cell/Ext cell/Model cell/util/spy cell/dom/data cell/dom/events cell/dom/mutate cell/util/fn cell/util/hash cell/util/type".split(" "),function(c,e,b,a,g,f,d,m,l,p){var h,n,k,t,q,s,r,w,x,y,z;x=a.watch;w=a.unwatch;r=a.suspendWatch;a=function(){};q=document;s=function(a){var b,c,f;b=0;for(c=a.length;b<c;)f=a[b++],p.isA(f)?s(f):d.remove(f)};k=function(){this.h={}};k.prototype={push:function(a,b){var c;((c=this.h)[a]||(c[a]=[])).push(b)},shift:function(a){var b;if(b=
this.h[a])return 1===b.lengh?(delete this.h[a],b[0]):b.shift()}};h=function(a,b,c){this.view=a;this.expr=b;this.renderer=c;this.hq=new k;this.parent=void 0};h.prototype.install=function(a){var b;this.parent=a;this.expr instanceof c?(b=this.expr,this.view.watch(function(){return b.toArray()},function(){n.call(this,this.expr)},this)):this.view.watch(this.expr,n,this)};n=function(a){var b,f,d,e,g,h;b=a instanceof c?a.toArray():a;h=new k;f=-1;for(g=b.length;++f<g;)d=b[f],e=l(d),h.push(e,this.view._rcs(this.hq.shift(e)||
this.renderer.call(this.view,d,f,a),this.parent));for(e in this.hq.h)s(this.hq.h[e]);this.hq=h};z=function(a,b){if(a)return new h(this.view,a,b)};y=function(a,b){var c,d,g,h,k,l,m;c=[].slice.call(arguments,1);d=-1;for(g=c.length;++d<g&&c[d]instanceof e;);g=c.splice(0,d);k=c.length&&c[0]&&c[0].constructor===Object?c.shift():{};if(p.isS(a)){if(d=/^(\w+)?(#([\w\-]+))?(\.[\w\.\-]+)?$/.exec(a))for(h in l=q.createElement(d[1]||"div"),d[3]&&l.setAttribute("id",d[3]),d[4]&&(d=d[4].slice(1).replace(/\./g,
" "),k["class"]=k["class"]?d+(" "+k["class"]):d),k)if(m=k[h],d=/^on(\w+)/.exec(h))f.on(l,d[1],m,this);else this.watch(m,function(a){"innerHTML"===this.k?l.innerHTML=a:l.setAttribute(this.k,a)},{k:h})}else a&&a.prototype instanceof t&&r(function(){return l=(new a(k)).el});if(l){this._rcs(c,l);for(d=g.length;d--;)g[d].run(l,this);return l}};return t=b.extend({constructor:function(a){var c,d;b.call(this);this.options=a?(this.model=a.model,this.collection=a.collection,delete a.model,delete a.collection,
a):{};this._=m.b(y,this);this._.view=this;this._.map=z;this.beforeRender();this.el=d=this.renderEl(this._);a=this._cellName;d.className=(c=d.className)?c+" "+a:a;g.set(d,"cellRef",this);d.setAttribute("cell",a);this._rcs(this.render(this._),d);this.afterRender()},beforeRender:a,renderEl:function(){return q.createElement("div")},render:a,afterRender:a,watch:function(a,b,c){x(this,a,b,c)},destroy:function(){this.el&&(b.prototype.destroy.call(this),w(this),d.remove(this.el),delete this.el)},_rc:function(a,
b,c,d){var f,e;a instanceof h?a.install(b):p.isF(a)?(f=[],this.watch(a,function(a){var c;if(null==a||0===a.length)a=[q.createTextNode("")];c=f.slice();f.length=0;this._rcs(a,b,c[0],f);s(c)}),d.push(f)):1===(e=a.nodeType)||3===e?d.push(b.insertBefore(a,c)):p.isA(a)?this._rcs(a,b,c,d):d.push(b.insertBefore(q.createTextNode(a),c))},_rcs:function(a,b,c,d){var f,e,g;null==c&&(c=null);null==d&&(d=[]);p.isA(a)||(a=[a]);e=0;for(g=a.length;e<g;e++)f=a[e],null!=f&&this._rc(f,b,c,d);return d}})});
define("views/Todo",["require","cell/exts/x_model","cell/exts/x_class","cell/defineView!"],function(c){var e,b;b=c("cell/exts/x_model");e=c("cell/exts/x_class");return c("cell/defineView!")({renderEl:function(a){return a("li",e({editing:function(){return this.get("editing")}}),a(".view",{ondblclick:this.edit},a("input.toggle",b("done"),{type:"checkbox"}),a("label",function(){return this.model.get("text")}),a("button.destroy",{onclick:function(){return this.model.destroy()}})),a("form",{onsubmit:this.submit},
this.input=a("input.edit",b("text"),{type:"text",onblur:this.blur})))},edit:function(){var a=this;this.set("editing",!0);setTimeout(function(){return a.input.focus()},0)},blur:function(a){this.set("editing",!1)},submit:function(a){a.preventDefault();this.blur()}})});window.__installedViews={"views/Todo":1,"views/App":1};
define("views/App","require models/Todos ./Todo cell/exts/x_class cell/dom/events cell/defineView!".split(" "),function(c){var e,b,a,g;b=c("models/Todos");e=c("./Todo");g=c("cell/exts/x_class");a=c("cell/dom/events");return new (c("cell/defineView!")({beforeRender:function(){a.on(window,"hashchange",this.onHashChange,this);this.onHashChange()},renderEl:function(){return document.body},render:function(a){return[a("section#todoapp",a("header#header",a("h1","todos"),a("input#new-todo",{placeholder:"What needs to be done?",
type:"text",onkeypress:function(a){13===a.keyCode&&(b.add({text:a.target.value,done:!1}),a.target.value="")}})),a("section#main",a("ul#todo-list",a.map(function(){return b.filterBy({done:this.get("filter")})},function(b){return a(e,{model:b})}))),a("footer#footer",a("span#todo-count",function(){return""+this.incompleteCount()+" item"+(1<this.incompleteCount()?"s":"")+" left"}),a("ul#filters",a("li",a("a",g({selected:function(){return null===this.get("filter")}}),{href:"#"},"All"),a("a",g({selected:function(){return!1===
this.get("filter")}}),{href:"#/active"},"Active"),a("a",g({selected:function(){return!0===this.get("filter")}}),{href:"#/completed"},"Completed"))),function(){if(this.completedCount())return a("button#clear-completed",{onclick:this.clearCompleted},"Clear completed ("+this.completedCount()+")")})),a("footer#info",a("p","Double-click to edit a todo."),a("p",a("a",{href:"http://twitter.com/peterwmwong"},"Peter Wong")),a("p","Part of ",a("a",{href:"http://todomvc.com"},"TodoMVC")))]},onHashChange:function(){this.set("filter",
function(){switch(window.location.hash){case "#/active":return!1;case "#/completed":return!0;default:return null}}())},incompleteCount:function(){return b.filterBy({done:!1}).length},clearCompleted:function(){var a,c,e,g;g=b.filterBy({done:!0});c=0;for(e=g.length;c<e;c++)a=g[c],a.destroy()},completedCount:function(){return b.length()-this.incompleteCount()}}))});require("views/App");
